env:
  global:
    - MONGO_CONN_STRING=mongodb+srv://dbadmin:SZARo4oZEL1gIHEZ@cluster0.lgzom.mongodb.net/testing?retryWrites=true&w=majority
language: node_js
node_js:
  - "15"
services:
  - docker
# branches:
#   only:
#     - master
cache:
  directories:
    - backend/node_modules
before_install:
  - cd backend
install:
  - npm install
script:
  - MONGO_CONN_STRING="mongodb+srv://dbadmin:SZARo4oZEL1gIHEZ@cluster0.lgzom.mongodb.net/testing?retryWrites=true&w=majority" npm test
  - cd ..
after_success:
  - ./scripts/check-branch.sh
  - docker build -t registry.heroku.com/unibuk/web app
  - docker build -t registry.heroku.com/unibuk-backend/web backend
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com
  - docker push registry.heroku.com/unibuk/web
  - docker push registry.heroku.com/unibuk-backend/web
  - ./scripts/publish-to-heroku.sh
