language: node_js
node_js:
  - "15"
services:
  - docker
before_install:
  - docker build -t registry.heroku.com/unibuk-backend/web backend
  - docker ps -a
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com

after_install:
  - docker push registry.heroku.com/unibuk-backend/web

script:
  - ./publish-to-heroku.sh
