language: node_js
node_js:
  - "15"
services:
  - docker
# branches:
#   only:
#     - master
before_install:
  - cd backend
install:
  - npm install
script:
  - npm test
after_success:
  - cd ..
  - docker build -t registry.heroku.com/unibuk/web app
  - docker build -t registry.heroku.com/unibuk-backend/web backend
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com
  - docker push registry.heroku.com/unibuk/web
  - docker push registry.heroku.com/unibuk-backend/web
  - ./publish-to-heroku.sh
