version: "3"
services:
  node:
    build: node
    command: node server.js
    volumes:
      - ./node:/usr/src/app
    ports:
      - "8080:8080"
  frontend:
    build: app
    ports:
      - "8000"
