version: "3"
services:
  backend:
    build: backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_CONN_STRING=mongodb+srv://dbadmin:arara@cluster0.lgrig.mongodb.net/se2-draft?retryWrites=true&w=majority
      - JWT_KEY=mpk
      - PORT=8080
  frontend:
    build: app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
