version: "3"
services:
  backend:
    build: backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_ATLAS_PW=arara
      - MONGO_ATLAS_NAME=se2-draft
      - JWT_KEY=mpk
      - PORT=8080
  frontend:
    build: app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
