# name: learn-github-actions
# on: [push]
# jobs:
#   check-bats-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#       - run: npm install -g bats
#       - run: bats -v

# on:
#   push:
#     branches:
#       - master

name: React Deployment
on: [push]
jobs:
  react-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install packages and Build 🔧
        run: |
          cd app
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: app/build
          CLEAN: true
